# Generated by Django 5.2.9 on 2026-05-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', '🟢 В сети'), ('away', '🟡 Отошёл'), ('busy', '🔴 Занят'), ('offline', '⚫ Не в сети')], default='online', max_length=20, verbose_name='Статус')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
