# Generated by Django 5.2.9 on 2026-05-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Текст сообщения')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.chatmessage', verbose_name='Ответ на')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_MESSAGE', 'Новое сообщение'), ('MENTION', 'Упоминание'), ('TICKET_UPDATE', 'Обновление заявки'), ('SYSTEM', 'Системное')], default='NEW_MESSAGE', max_length=50, verbose_name='Тип')),
                ('content', models.CharField(max_length=500, verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.chatmessage', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление чата',
                'verbose_name_plural': 'Уведомления чатов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('PRIVATE', 'Личная переписка'), ('GROUP', 'Групповой чат'), ('CHANNEL', 'Канал'), ('SUPPORT', 'Техподдержка')], default='GROUP', max_length=20, verbose_name='Тип чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('avatar_url', models.TextField(blank=True, null=True, verbose_name='Аватар (URL)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.chatmessage')),
            ],
            options={
                'verbose_name': 'Чат-комната',
                'verbose_name_plural': 'Чат-комнаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chatroom', verbose_name='Чат'),
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('role_in_chat', models.CharField(choices=[('OWNER', 'Владелец'), ('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('MEMBER', 'Участник')], default='MEMBER', max_length=50, verbose_name='Роль в чате')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Уведомления выключены')),
                ('nickname_in_chat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Никнейм в чате')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.chatmessage')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.chatroom', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш файла')),
                ('download_count', models.IntegerField(default=0, verbose_name='Скачиваний')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.chatmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрепления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='messaging.chatroom', verbose_name='Чат')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned', to='messaging.chatmessage', verbose_name='Сообщение')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Закрепил')),
            ],
            options={
                'verbose_name': 'Закрепленное сообщение',
                'verbose_name_plural': 'Закрепленные сообщения',
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'sent_at'], name='messaging_c_chat_id_5522d9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'sent_at'], name='messaging_c_sender__79f0c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmembership',
            unique_together={('user', 'chat')},
        ),
    ]
