# Generated by Django 5.2.9 on 2026-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatmessage_chatnotification_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/', verbose_name='Файл'),
        ),
    ]
